# frozen_string_literal: true

require_relative 'helper'
require_relative 'support/helpers'
require 'fluent/plugin/azure_logs_ingestion/payload_builder'
require 'zlib'

class PayloadBuilderTest < Test::Unit::TestCase
  test 'does not inject TimeGenerated by default' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: false)

    begin
      result = builder.build(FakeChunk.new([
        [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 0, 0)), { 'message' => 'hello' }]
      ]))

      body = result.io.read
      assert_match(/"message":"hello"/, body)
      assert_not_match(/"TimeGenerated":/, body)
    ensure
      result&.close!
    end
  end

  test 'builds payload from event time' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: false)

    begin
      result = builder.build(FakeChunk.new([
        [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 0, 0)), { 'message' => 'hello' }]
      ]))

      body = result.io.read
      assert_match(/"message":"hello"/, body)
      assert_equal 1, result.record_count
      assert_equal result.raw_size, result.content_length
    ensure
      result&.close!
    end
  end

  test 'accepts wide time span' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: false)

    result = builder.build(FakeChunk.new([
      [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 0, 0)), {}],
      [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 31, 0)), {}]
    ]))

    assert_equal 2, result.record_count
    result&.close!
  end

  test 'builds gzip payload when enabled' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: true)

    begin
      result = builder.build(FakeChunk.new([
        [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 0, 0)), { 'message' => 'hello' }]
      ]))

      json = Zlib::GzipReader.new(result.io).read
      assert_equal 'gzip', result.content_encoding
      assert_match(/"message":"hello"/, json)
      assert_not_nil result.gzip_size
    ensure
      result&.io&.rewind
      result&.close!
    end
  end

  test 'rejects oversized payload' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: false)

    error = assert_raise(Fluent::UnrecoverableError) do
      builder.build(FakeChunk.new([
        [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 0, 0)), { 'message' => 'a' * 1_100_000 }]
      ]))
    end

    assert_match(/payload size/, error.message)
  end

  test 'accepts non-parseable event time when payload is otherwise valid' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: false)

    begin
      result = builder.build(FakeChunk.new([
        ['not-a-time', { 'message' => 'hello' }]
      ]))

      assert_match(/"message":"hello"/, result.io.read)
    ensure
      result&.close!
    end
  end

  test 'accepts payload records with existing TimeGenerated' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: false)

    begin
      result = builder.build(FakeChunk.new([
        ['not-a-time', { 'message' => 'hello', 'TimeGenerated' => '2026-01-01T00:00:00Z' }]
      ]))

      body = result.io.read
      assert_match(/"TimeGenerated":"2026-01-01T00:00:00Z"/, body)
    ensure
      result&.close!
    end
  end

  test 'rejects oversized gzip payload' do
    builder = Fluent::Plugin::AzureLogsIngestion::PayloadBuilder.new(gzip: true)

    error = assert_raise(Fluent::UnrecoverableError) do
      builder.build(FakeChunk.new([
        [Fluent::EventTime.from_time(Time.utc(2026, 1, 1, 0, 0, 0)), { 'message' => 'a' * 1_100_000 }]
      ]))
    end

    assert_match(/payload size|gzip payload size/, error.message)
  end
end
